from pathlib import Path

path = Path('/home/ubuntu/wa-chat-studio/client/src/pages/Home.tsx')
source = path.read_text()
source = source.replace(
    '<nav className="wf-nav secondary"><button onClick={() => notify("Knowledge source manager opened", "info")}><Database size={16} /><span>Knowledge sources</span></button><button onClick={() => notify("Permission matrix opened", "info")}><ShieldCheck size={16} /><span>Permissions</span></button><button onClick={() => notify("Audit log is ready to inspect", "info")}><Fingerprint size={16} /><span>Audit log</span></button></nav>',
    '<nav className="wf-nav secondary"><button onClick={() => setActiveNav("knowledge")}><Database size={16} /><span>Knowledge sources</span></button><button onClick={() => notify("Permission matrix is enforced per agent", "info")}><ShieldCheck size={16} /><span>Permissions</span></button><button onClick={() => setActiveNav("audit")}><Fingerprint size={16} /><span>Audit log</span></button></nav>'
)
source = source.replace(
    '<label>Agent name<input autoFocus value={newAgentName} onChange={(event) => setNewAgentName(event.target.value)} placeholder="e.g. Atlas Research" /></label>',
    '<label>Agent name<input autoFocus value={newAgentName} onChange={(event) => setNewAgentName(event.target.value)} placeholder="e.g. Atlas Research" /></label><label>Role<input value={newAgentRole} onChange={(event) => setNewAgentRole(event.target.value)} placeholder="e.g. Research Lead" /></label>'
)
source = source.replace(
    '<span className="eyebrow">WORKFORCE BUILDER</span><h2>Create an agent</h2>',
    '<span className="eyebrow">WORKFORCE BUILDER</span><h2>{editingAgentId ? "Edit an agent" : "Create an agent"}</h2>'
)
source = source.replace(
    '<button className="primary-button" disabled={!newAgentName.trim()} onClick={addAgent}><Bot size={15} />Create draft</button>',
    '<button className="primary-button" disabled={!newAgentName.trim()} onClick={addAgent}><Bot size={15} />{editingAgentId ? "Save changes" : "Create draft"}</button>'
)
marker = 'function CommandCenter('
head = source.split(marker, 1)[0]
tail = r'''type ApprovalItem = { id: number; action: string; rationale: string; status: string };
type PersistedDepartment = { id: number; name: string; purpose: string; color: string; status: string };
type PersistedWorkflow = { id: number; name: string; description: string; trigger: string; status: string; requiresApproval: boolean };
type PersistedKnowledge = { id: number; title: string; sourceType: string; uri: string | null; status: string; chunkCount: number };
type AuditItem = { id: number; action: string; resourceType: string; resourceId: string | null; outcome: string; createdAt: Date | string; details: unknown };

function CommandCenter({ messages, prompt, setPrompt, sendPrompt, activeAgent, setActiveAgentId, filteredAgents, agentSearch, setAgentSearch, selectedDepartment, setSelectedDepartment, showInfo, setShowInfo, isAuthenticated, planPending, streamPhase, approvals, onDecideApproval }: { messages: WorkforceMessage[]; prompt: string; setPrompt: (value: string) => void; sendPrompt: () => void; activeAgent: Agent; setActiveAgentId: (id: string) => void; filteredAgents: Agent[]; agentSearch: string; setAgentSearch: (value: string) => void; selectedDepartment: string; setSelectedDepartment: (value: string) => void; showInfo: boolean; setShowInfo: (value: boolean) => void; isAuthenticated: boolean; planPending: boolean; streamPhase: string; approvals: ApprovalItem[]; onDecideApproval: (id: number, status: "approved" | "rejected") => void }) {
  return <div className="command-grid">
    <aside className="people-rail"><div className="rail-heading"><div><span className="section-kicker">AI CONTACTS</span><strong>Workforce</strong></div><button className="small-plus" title="Add agent"><Plus size={15} /></button></div><div className="rail-search"><Search size={14} /><input value={agentSearch} onChange={(event) => setAgentSearch(event.target.value)} placeholder="Find an agent" /></div><div className="rail-filters"><button className={selectedDepartment === "all" ? "active" : ""} onClick={() => setSelectedDepartment("all")}>All</button><button className={selectedDepartment === "Executive Office" ? "active" : ""} onClick={() => setSelectedDepartment("Executive Office")}>Core</button><button className={selectedDepartment === "Growth & Marketing" ? "active" : ""} onClick={() => setSelectedDepartment("Growth & Marketing")}>Growth</button></div><div className="people-list">{filteredAgents.map((agent) => <button className={`person-row ${activeAgent.id === agent.id ? "selected" : ""}`} key={agent.id} onClick={() => setActiveAgentId(agent.id)}><div className={avatarClass(agent.accent)}>{agent.avatar}<span className={`presence ${agent.status}`} /></div><div><strong>{agent.name}</strong><span>{agent.role}</span><small>{agent.last}</small></div>{agent.status === "working" && <CircleDot size={13} className="working-icon" />}</button>)}</div><div className="rail-footer"><div><span>WORKFORCE CAPACITY</span><strong>68%</strong></div><div className="capacity"><span style={{ width: "68%" }} /></div><small>{filteredAgents.length} visible agents · persistent workspace</small></div></aside>
    <section className="right-hand-chat"><div className="chat-top"><div className="chat-identity"><div className={avatarClass(activeAgent.accent)}>{activeAgent.avatar}<span className={`presence ${activeAgent.status}`} /></div><div><strong>{activeAgent.name}</strong><span>{activeAgent.role}</span></div></div><div className="chat-top-actions"><span className="mode-tag"><Network size={12} /> orchestrated</span><button className="top-icon"><Search size={16} /></button><button className="top-icon"><MoreHorizontal size={16} /></button></div></div><div className="chat-body"><div className="secure-note"><ShieldCheck size={13} /> agent communication is permission-aware and auditable</div><div className="day-marker">TODAY · TUESDAY, SEPTEMBER 8</div>{messages.map((message) => <div className={`wf-message ${message.from === "user" ? "from-user" : ""} ${message.kind === "plan" ? "is-plan" : ""}`} key={message.id}><div className="message-label"><span>{message.sender}</span><time>{message.time}</time></div><div className="message-card">{message.kind === "plan" && <div className="plan-header"><div><Zap size={14} /><strong>Execution plan ready</strong></div><span>LangGraph state · queued</span></div>}<p>{message.body}</p>{message.kind === "plan" && <div className="plan-steps"><span><CheckCircle2 size={13} /> Route agents</span><span><CheckCircle2 size={13} /> Write memory</span><span><Clock3 size={13} /> Approval gate</span></div>}{message.from === "system" && <div className="signal-bar"><Activity size={13} /> live workforce signal <ArrowUpRight size={13} /></div>}</div></div>)}{planPending && <div className="thinking-row"><div className="thinking-dots"><span /><span /><span /></div><span>Ari is {streamPhase || "planning across the workforce"}…</span></div>}</div><div className="prompt-dock"><div className="prompt-suggestions"><button onClick={() => setPrompt("Prepare a concise Q2 growth plan with research, owners, and risks")}>Prepare a growth plan</button><button onClick={() => setPrompt("Find the most important decision I should make this week")}>What needs my attention?</button></div><div className="prompt-box"><Sparkles size={17} className="prompt-spark" /><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); sendPrompt(); } }} placeholder="Tell your company what to do next…" rows={1} /><button className={prompt.trim() ? "send-ready" : ""} onClick={sendPrompt} title={isAuthenticated ? "Run with Right Hand" : "Try demo plan"}>{planPending ? <RefreshCw size={17} className="spin" /> : <Send size={17} />}</button></div><div className="prompt-hint"><LockKeyhole size={11} /> {isAuthenticated ? "Live orchestration enabled" : "Demo mode · sign in to enable live orchestration"}<span>•</span> Enter to send</div></div></section>
    {showInfo && <aside className="operating-panel"><div className="panel-heading"><div><span className="section-kicker">OPERATING SYSTEM</span><strong>Live overview</strong></div><button className="top-icon" onClick={() => setShowInfo(false)}><X size={15} /></button></div><div className="pulse-card"><div className="pulse-orb"><div className="pulse-ring ring-a" /><div className="pulse-ring ring-b" /><BrainCircuit size={22} /></div><div><span>RIGHT HAND PULSE</span><strong>Everything is moving</strong><small>Queue · durable when Redis is configured</small></div></div><div className="metric-grid"><div><span>Agents visible</span><strong>{filteredAgents.length}</strong><em>Persisted workspace</em></div><div><span>Approval queue</span><strong>{approvals.length}</strong><em>Actions below</em></div><div><span>Memory health</span><strong>94%</strong><em>Scoped knowledge</em></div><div><span>Audit events</span><strong>60</strong><em>Latest events retained</em></div></div><div className="panel-section"><div className="section-title"><span>Approval queue</span><b>{approvals.length} pending</b></div>{approvals.length === 0 && <div className="empty-inline"><CheckCircle2 size={14} /> No pending approval actions</div>}{approvals.slice(0, 3).map((approval) => <div className="approval-item" key={approval.id}><div className="approval-icon amber"><Globe2 size={14} /></div><div><strong>{approval.action}</strong><span>{approval.rationale}</span></div><div className="approval-actions"><button className="approve-button" onClick={() => onDecideApproval(approval.id, "approved")}><Check size={13} /></button><button className="reject-button" onClick={() => onDecideApproval(approval.id, "rejected")}><X size={13} /></button></div></div>)}</div><div className="panel-section"><div className="section-title"><span>Recent activity</span><span className="runtime-chip">approval-aware</span></div><div className="activity-line"><div className="activity-dot mint" /><div><strong>Right Hand plans are audited</strong><span>Every plan emits a workspace event</span></div></div><div className="activity-line"><div className="activity-dot blue" /><div><strong>Tool runs are durable</strong><span>Input, output, status, and errors tracked</span></div></div></div><button className="close-panel" onClick={() => setShowInfo(false)}>Hide live overview <ChevronDown size={13} /></button></aside>}
  </div>;
}

function AgentsView({ agents, filteredAgents, agentSearch, setAgentSearch, setActiveAgentId, setActiveNav, onEditAgent }: { agents: Agent[]; filteredAgents: Agent[]; agentSearch: string; setAgentSearch: (value: string) => void; setActiveAgentId: (id: string) => void; setActiveNav: (value: string) => void; onEditAgent: (agent: Agent) => void }) {
  return <div className="directory-view"><div className="directory-toolbar"><div className="toolbar-search"><Search size={15} /><input value={agentSearch} onChange={(event) => setAgentSearch(event.target.value)} placeholder="Search roles, expertise, or departments" /></div><div className="toolbar-meta"><span>Showing {filteredAgents.length} of {agents.length}</span><button className="outline-button"><Archive size={14} />Filters</button></div></div><div className="agent-grid">{filteredAgents.map((agent) => <div className="agent-card" key={agent.id} onClick={() => { setActiveAgentId(agent.id); setActiveNav("command"); }}><div className="agent-card-top"><div className={avatarClass(agent.accent)}>{agent.avatar}<span className={`presence ${agent.status}`} /></div><span className={`status-tag ${agent.status}`}>{agent.status}</span></div><div className="agent-card-copy"><h3>{agent.name}</h3><p>{agent.role}</p><span className="agent-dept"><FolderKanban size={12} />{agent.dept}</span></div><div className="expertise-list">{agent.expertise.map((skill) => <span key={skill}>{skill}</span>)}</div><div className="agent-card-footer"><span><BrainCircuit size={12} /> memory linked</span><button className="top-icon" title="Edit agent" onClick={(event) => { event.stopPropagation(); onEditAgent(agent); }}><Settings2 size={14} /></button></div></div>)}</div></div>;
}

function DepartmentsView({ setActiveNav, departments, onCreate, onEdit }: { setActiveNav: (value: string) => void; departments: PersistedDepartment[]; onCreate: () => void; onEdit: (id: number, name: string) => void }) {
  const cards = departments.length ? departments.map((department) => ({ ...department, count: 0, trend: department.status })) : departmentSeed.map((department) => ({ ...department, id: department.id, count: department.count, trend: department.trend, status: "active" }));
  return <div className="directory-view"><div className="dept-summary"><div><span className="section-kicker">ORGANIZATIONAL DESIGN</span><h2>Each department has a mission.</h2><p>Ari can create, staff, and reconfigure departments as your goals change.</p></div><button className="primary-button" onClick={onCreate}><Plus size={15} />Add department</button></div><div className="department-grid">{cards.map((dept) => <div className="department-card" key={String(dept.id)} onClick={() => setActiveNav("agents")}><div className={`dept-mark ${dept.color}`}><Network size={18} /></div><div className="department-card-copy"><span>{dept.count} AI agents · {dept.status}</span><h3>{dept.name}</h3><p>{dept.purpose}</p></div><div className="dept-footer"><span>{dept.trend}</span>{typeof dept.id === "number" && <button className="top-icon" title="Edit department" onClick={(event) => { event.stopPropagation(); onEdit(dept.id as number, dept.name); }}><Settings2 size={14} /></button>}</div></div>)}</div><div className="architecture-card"><div className="arch-copy"><span className="section-kicker">AUTONOMOUS ORGANIZATION</span><h2>One Right Hand. Many specialized minds.</h2><p>Every agent inherits workspace guardrails, then adds its own role, memory, tools, and permission boundary. Collaboration happens in context — not in a maze of disconnected bots.</p></div><div className="arch-orbit"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-core"><BrainCircuit size={23} /><span>Ari</span></div><div className="orbit-node node-a">M</div><div className="orbit-node node-b">E</div><div className="orbit-node node-c">N</div></div></div></div>;
}

function WorkflowsView({ workflows, onCreate, onRun }: { workflows: PersistedWorkflow[]; onCreate: () => void; onRun: (id: number) => void }) {
  const cards = workflows.length ? workflows.map((flow) => ({ ...flow, owner: "Persisted workforce", progress: flow.status === "active" ? 72 : flow.status === "paused" ? 34 : 12, next: flow.requiresApproval ? "Approval-aware" : "Ready" })) : workflowSeed.map((flow) => ({ ...flow, id: 0, description: flow.name, trigger: flow.next, requiresApproval: flow.status === "Waiting approval" }));
  return <div className="directory-view"><div className="workflow-summary"><div><span className="section-kicker">AUTOMATION LAYER</span><h2>Workflows that keep moving.</h2><p>LangGraph state, approval gates, durable runs, and visible handoffs — all in one operating view.</p></div><button className="primary-button" onClick={onCreate}><Plus size={15} />New workflow</button></div><div className="workflow-list">{cards.map((flow) => { const Icon = "icon" in flow ? flow.icon : Workflow; return <div className="workflow-card" key={`${flow.name}-${flow.id}`}><div className={`workflow-icon ${"color" in flow ? flow.color : "mint"}`}><Icon size={18} /></div><div className="workflow-copy"><div className="workflow-title"><h3>{flow.name}</h3><span className={`workflow-status ${String(flow.status).toLowerCase().replace(" ", "-")}`}>{flow.status}</span></div><p>Owned by {flow.owner} · {flow.next}</p><div className="progress-track"><span style={{ width: `${flow.progress}%` }} /></div></div><div className="workflow-percent">{flow.progress}%<small>complete</small></div>{"id" in flow && flow.id > 0 && <button className="outline-button" onClick={() => onRun(flow.id as number)}><Zap size={13} />Run</button>}</div>; })}</div><div className="workflow-architecture"><div className="workflow-arch-head"><div><span className="section-kicker">GRAPH RUNTIME</span><h3>Planning → routing → approval → execution</h3></div><span className="runtime-chip"><GitBranch size={13} /> LangGraph foundation</span></div><div className="flow-steps"><div className="flow-step done"><span>01</span><strong>Understand</strong><small>Intent + context</small></div><div className="flow-connector active" /><div className="flow-step done"><span>02</span><strong>Route</strong><small>Best-fit agents</small></div><div className="flow-connector active" /><div className="flow-step waiting"><span>03</span><strong>Approval gate</strong><small>Human when needed</small></div><div className="flow-connector" /><div className="flow-step"><span>04</span><strong>Execute</strong><small>Tools + memory</small></div><div className="flow-connector" /><div className="flow-step"><span>05</span><strong>Audit</strong><small>Trace everything</small></div></div></div></div>;
}

function MemoryView({ onCreate, knowledge }: { onCreate: () => void; knowledge: PersistedKnowledge[] }) {
  return <div className="directory-view"><div className="memory-hero"><div><span className="section-kicker">SHARED INTELLIGENCE</span><h2>Your company remembers what matters.</h2><p>Long-term memory is scoped, attributable, and permission-aware — so every agent knows more without knowing too much.</p></div><div className="memory-score"><span>MEMORY HEALTH</span><strong>94<span>%</span></strong><small>{knowledge.length} persisted sources</small></div></div><div className="memory-toolbar"><div className="toolbar-search"><Search size={15} /><input placeholder="Search memory, knowledge, and policies" /></div><button className="outline-button" onClick={onCreate}><FileText size={14} />Add knowledge</button></div><div className="memory-list">{(knowledge.length ? knowledge.map((item) => ({ title: item.title, type: item.sourceType, agent: "Workspace", updated: item.status, score: 100 })) : memorySeed).map((memory) => <div className="memory-row" key={memory.title}><div className="memory-kind"><BrainCircuit size={15} /></div><div className="memory-copy"><h3>{memory.title}</h3><span>{memory.type} · owned by {memory.agent}</span></div><div className="memory-score-mini"><strong>{memory.score}</strong><span>relevance</span></div><div className="memory-updated">{memory.updated}</div><button className="top-icon"><MoreHorizontal size={16} /></button></div>)}</div><div className="memory-footnote"><LockKeyhole size={14} /> Memory writes follow workspace permissions and are visible in the audit log.</div></div>;
}

function KnowledgeView({ knowledge, onCreate, onUpdate }: { knowledge: PersistedKnowledge[]; onCreate: () => void; onUpdate: (id: number, title: string) => void }) {
  return <div className="directory-view"><div className="workflow-summary"><div><span className="section-kicker">KNOWLEDGE SOURCES</span><h2>Give every agent the right context.</h2><p>Knowledge sources are scoped to your workspace and can be updated without touching agent prompts.</p></div><button className="primary-button" onClick={onCreate}><Plus size={15} />Add source</button></div><div className="memory-list">{knowledge.length === 0 && <div className="empty-resource"><Database size={17} />No persisted knowledge yet. Add a note to create the first source.</div>}{knowledge.map((item) => <div className="memory-row" key={item.id}><div className="memory-kind"><Database size={15} /></div><div className="memory-copy"><h3>{item.title}</h3><span>{item.sourceType} · {item.chunkCount} chunks · {item.status}</span></div><div className="memory-updated">{item.status}</div><button className="top-icon" onClick={() => { const title = window.prompt("Source title", item.title); if (title?.trim()) onUpdate(item.id, title.trim()); }}><Settings2 size={14} /></button></div>)}</div></div>;
}

function AuditView({ audit }: { audit: AuditItem[] }) {
  return <div className="directory-view"><div className="workflow-summary"><div><span className="section-kicker">AUDIT LOG</span><h2>Every decision leaves a trace.</h2><p>Resource mutations, tool runs, approval decisions, and workflow state transitions are retained for review.</p></div><span className="runtime-chip"><Fingerprint size={13} /> {audit.length} events loaded</span></div><div className="memory-list">{audit.length === 0 && <div className="empty-resource"><Fingerprint size={17} />Sign in and start creating resources to populate the audit trail.</div>}{audit.map((item) => <div className="memory-row" key={item.id}><div className="memory-kind"><Activity size={15} /></div><div className="memory-copy"><h3>{item.action}</h3><span>{item.resourceType} · {item.resourceId ?? "workspace"} · {String(item.outcome)}</span></div><div className="memory-updated">{new Date(item.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div><button className="top-icon"><MoreHorizontal size={16} /></button></div>)}</div></div>;
}
'''
path.write_text(head + tail)
